<a href="https://colab.research.google.com/github/anaisrcast/Data-Science-Practice/blob/main/SalesData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
import pandas as pd
print("Import Complete")

Import Complete

In [97]:
sales_df = pd.read_csv("messy_ecommerce_sales_data.csv")
sales_df.head(5)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [98]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      103 non-null    object
 4   Product         103 non-null    object
 5    Category       95 non-null     object
 6   Quantity        98 non-null     object
 7   Price           98 non-null     object
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), object(9)
memory usage: 9.0+ KB

---
#NEXT STEPS:
- Column names have additional spaces in the naming convention
- There a number of nulls rows within 'Category', 'Quantity', 'Price', 'Total'
- Data types for 'Order_Date', 'Quanity'and 'Price' need to updated accordingly

In [99]:
#strip the column headers
sales_df.columns = sales_df.columns.str.strip()

#Correct data types
#------------
#Date
sales_df['Order_Date'] = pd.to_datetime(sales_df['Order_Date'], format='mixed',errors='coerce')
#Float Price
sales_df['Price'] = pd.to_numeric(sales_df['Price'], errors = "coerce")
#Interger Quantity
sales_df['Quantity'] = pd.to_numeric(sales_df['Quantity'], errors = "coerce")

#+ rows with make them all the same case
if sales_df['Category'].dtype == 'object':
    sales_df['Category'] = sales_df['Category'].str.lower()

In [100]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1   Customer_Name   103 non-null    object
 2   Order_ID        103 non-null    object
 3   Order_Date      102 non-null    datetime64[ns]
 4   Product         103 non-null    object
 5   Category        95 non-null     object
 6   Quantity        97 non-null     float64
 7   Price           94 non-null     float64
 8   Payment_Method  103 non-null    object
 9   Status          103 non-null    object
 10  Total           89 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 9.0+ KB

Notes: Additional nulls have appeared once the data types were updated
---
# Next Steps:
- Investigate null rows to see if it is possible to replace or remove

In [101]:
sales_df[sales_df['Order_Date'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
92,192,Customer_192,ORD-35144,NaT,Jacket,clothing,NaN,203.63,Credit Card,Returned,NaN

Delete null in 'Order_Date' column since it is only one row and the Order_date, Quantity and Total is missing

In [102]:
sales_df = sales_df.dropna(subset = ['Order_Date'])
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 102 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              102 non-null    int64
 1   Customer_Name   102 non-null    object
 2   Order_ID        102 non-null    object
 3   Order_Date      102 non-null    datetime64[ns]
 4   Product         102 non-null    object
 5   Category        94 non-null     object
 6   Quantity        97 non-null     float64
 7   Price           93 non-null     float64
 8   Payment_Method  102 non-null    object
 9   Status          102 non-null    object
 10  Total           89 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 9.6+ KB

Will investigate nulls in the 'Category' column

In [103]:
sales_df[sales_df['Category'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
33,133,Customer_133,ORD-68182,2024-12-05,Biography,NaN,5.0,343.24,Credit Card,Shipped,1716.20
36,136,Customer_136,ORD-20985,2025-06-12,Headphones,NaN,1.0,696.71,Credit Card,Delivered,696.71
80,180,Customer_180,ORD-86629,2025-03-26,Laptop,NaN,2.0,418.38,Credit Card,Processing,836.76
81,181,Customer_181,ORD-54481,2024-12-29,Smartphone,NaN,1.0,266.48,Cash on Delivery,Cancelled,266.48
82,182,Customer_182,ORD-79672,2025-08-03,Shoes,NaN,4.0,538.35,PayPal,Processing,2153.40
84,184,Customer_184,ORD-67799,2025-02-15,Jeans,NaN,4.0,101.19,Bank Transfer,Processing,404.76
93,193,Customer_193,ORD-42475,2025-06-06,Basketball,NaN,NaN,522.02,PayPal,Shipped,NaN
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,NaN,2.0,497.01,Cash on Delivery,Shipped,994.02

# Want to create a dimension table to match up the different products and category

Will use the dimenstion table to fill in the nulls within the original dataset if there is a match OR no repeats

In [104]:
#Grabbing the Products for the Categories that are null to use later...
Product_Nulls = sales_df[sales_df['Category'].isnull()]['Product'].unique()
print(Product_Nulls)

['Biography' 'Headphones' 'Laptop' 'Smartphone' 'Shoes' 'Jeans'
 'Basketball' 'Vacuum']

In [105]:
#Creating the dimension table with Products and Categories
prod_cat_df = sales_df[['Product', 'Category']].dropna()
prod_cat_df = prod_cat_df.drop_duplicates()
prod_cat_df = prod_cat_df.sort_values(['Product', 'Category'])

In [106]:
prod_cat_df[prod_cat_df['Product'].isin(Product_Nulls)]

       Product     Category
46  Basketball   electronic
10  Basketball       sports
4    Biography        books
75  Headphones  electronics
56       Jeans     clothing
45      Laptop  electronics
12       Shoes     clothing
1   Smartphone  electronics
23      Vacuum   electronic
37      Vacuum         home

**Can** fill in the products for Headphones, Jeans, Laptop, Shoes, Smartphone

I hesitate to fill in 'Basketball' Product since there are 2 different categories and the Kaggle description does not clarify the different categories. Can see this fit into NBA 2k (electronic) and a basketball (sports). Will drop the rows with the 'Basketball' Product with null Categories since there is no clear direction.

Will combine the Vacuum products to consolidate into one category, arbitrarily chose 'home' since there is not direction in the kaggle dataset

In [107]:
#change vacuum to the same category
sales_df.loc[sales_df['Product'] == 'Vacuum', 'Category'] = 'home'
#recreate dimension table
prod_cat_df = sales_df[['Product', 'Category']].dropna()
prod_cat_df = prod_cat_df.drop_duplicates()
prod_cat_df = prod_cat_df.sort_values(['Product', 'Category'])
#drop basketball products
prod_cat_df = prod_cat_df.loc[prod_cat_df['Product'] != 'Basketball']
#View new dimension table
prod_cat_df[prod_cat_df['Product'].isin(Product_Nulls)]

       Product     Category
4    Biography        books
75  Headphones  electronics
56       Jeans     clothing
45      Laptop  electronics
12       Shoes     clothing
1   Smartphone  electronics
23      Vacuum         home

In [108]:
#Lookup the nulls in the new dimension table!
cat_lookup = prod_cat_df.set_index('Product').to_dict()['Category']
sales_df['Category'] = sales_df['Category'].fillna(sales_df['Product'].map(cat_lookup))
#drop nas in Category column
sales_df = sales_df.dropna(subset = ['Category'])
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 101 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              101 non-null    int64
 1   Customer_Name   101 non-null    object
 2   Order_ID        101 non-null    object
 3   Order_Date      101 non-null    datetime64[ns]
 4   Product         101 non-null    object
 5   Category        101 non-null    object
 6   Quantity        97 non-null     float64
 7   Price           92 non-null     float64
 8   Payment_Method  101 non-null    object
 9   Status          101 non-null    object
 10  Total           89 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 9.5+ KB

In [109]:
#double checking it filled in correctly
sales_df[sales_df['Customer_Name'] == 'Customer_198']

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
98,198,Customer_198,ORD-14608,2025-07-27,Vacuum,home,2.0,497.01,Cash on Delivery,Shipped,994.02

Will now look at the nulls in the 'Quantity' column

In [110]:
sales_df[sales_df['Quantity'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
6,106,Customer_106,ORD-25885,2025-02-02,Blender,home,NaN,978.63,Bank Transfer,Processing,NaN
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,sports,NaN,587.64,Credit Card,Returned,NaN
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,sports,NaN,593.93,Cash on Delivery,Processing,NaN
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,home,NaN,NaN,PayPal,Delivered,NaN

In [111]:
#Fill in the Qunatities based on Product, Category duo + round to the nearest whole number
sales_df['Quantity'] = sales_df['Quantity'].fillna(
    sales_df.groupby(['Product', 'Category'])['Quantity'].transform('mean').round(0)
)
#double check everything filled in correctly
sales_df[sales_df['Customer_Name'] == 'Customer_106']

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
6,106,Customer_106,ORD-25885,2025-02-02,Blender,home,4.0,978.63,Bank Transfer,Processing,NaN

Will now look at the Null rows in the 'Price' Column

In [112]:
sales_df[sales_df['Price'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,electronics,2.0,NaN,PayPal,Processing,NaN
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,sports,5.0,NaN,Cash on Delivery,Cancelled,NaN
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,home,4.0,NaN,Cash on Delivery,Processing,NaN
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,electronics,5.0,NaN,Credit Card,Cancelled,NaN
24,124,Customer_124,ORD-46136,2025-05-31,Comics,books,5.0,NaN,PayPal,Cancelled,NaN
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,sports,2.0,NaN,Bank Transfer,Processing,NaN
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,clothing,2.0,NaN,Bank Transfer,Shipped,NaN
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,clothing,5.0,NaN,Cash on Delivery,Returned,NaN
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,home,2.0,NaN,PayPal,Delivered,NaN

In [113]:
sales_df['Price'] = sales_df['Price'].fillna(
    sales_df.groupby(['Product', 'Category'])['Price'].transform('mean').round(2)
)
#double check everything filled in correctly
sales_df[sales_df['Customer_Name'] == 'Customer_101']

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,electronics,2.0,560.99,PayPal,Processing,NaN

Will look at the Total column for nulls

In [114]:
sales_df[sales_df['Total'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,electronics,2.0,560.99,PayPal,Processing,NaN
6,106,Customer_106,ORD-25885,2025-02-02,Blender,home,4.0,978.63,Bank Transfer,Processing,NaN
10,110,Customer_110,ORD-61020,2025-09-26,Basketball,sports,5.0,534.32,Cash on Delivery,Cancelled,NaN
16,116,Customer_116,ORD-63660,2025-10-30,Microwave,home,4.0,408.05,Cash on Delivery,Processing,NaN
20,120,Customer_120,ORD-14659,2025-06-13,Yoga Mat,electronics,5.0,266.70,Credit Card,Cancelled,NaN
24,124,Customer_124,ORD-46136,2025-05-31,Comics,books,5.0,743.05,PayPal,Cancelled,NaN
30,130,Customer_130,ORD-34007,2025-08-15,Tennis Racket,sports,2.0,400.04,Bank Transfer,Processing,NaN
56,156,Customer_156,ORD-34679,2024-11-28,Jeans,clothing,2.0,421.41,Bank Transfer,Shipped,NaN
64,164,Customer_164,ORD-23010,2025-02-09,Tennis Racket,sports,2.0,587.64,Credit Card,Returned,NaN
67,167,Customer_167,ORD-30329,2025-08-07,Basketball,sports,4.0,593.93,Cash on Delivery,Processing,NaN
83,183,Customer_183,ORD-20916,2025-03-10,Shoes,clothing,5.0,649.94,Cash on Delivery,Returned,NaN
96,196,Customer_196,ORD-78384,2024-12-23,Vacuum,home,2.0,483.32,PayPal,Delivered,NaN

In [115]:
sales_df['Total'] = sales_df['Total'].fillna(
    sales_df['Quantity'] * sales_df['Price']
)
#double check everything filled in correctly
sales_df[sales_df['Customer_Name'] == 'Customer_101']

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
1,101,Customer_101,ORD-35783,2025-07-05,Smartphone,electronics,2.0,560.99,PayPal,Processing,1121.98

In [116]:
#double check there is NO more nulls to clean
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 101 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              101 non-null    int64
 1   Customer_Name   101 non-null    object
 2   Order_ID        101 non-null    object
 3   Order_Date      101 non-null    datetime64[ns]
 4   Product         101 non-null    object
 5   Category        101 non-null    object
 6   Quantity        101 non-null    float64
 7   Price           101 non-null    float64
 8   Payment_Method  101 non-null    object
 9   Status          101 non-null    object
 10  Total           101 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 9.5+ KB

# Clean is complete!

---

#Next step:
- Analysis